# 起点与终点
DEPART_POS : [0., -9., 0.2]          # 起点的坐标
DEPART_EULER : [0., 0., 1.5707963]  # 起点处机器人的位姿的欧拉角表示
TARGET_POS : [0., 9., 0.2]           # 终点的坐标

# reward中的参数
# COLLISION_REWARD : -8              # 碰撞一次的奖励值（负数代表惩罚）
# REACH_TARGET_REWARD : 1000000       # 到达终点的奖励
# TARGET_RADIUS : 2.5                 # 终点的领域半径
# DISTANCE_CHANGE_REWARD_COE : 100    # 每次离终点距离和上一次比较的差值的奖励系数

# 原文指标
COLLISION_REWARD : -1000              # 碰撞一次的奖励值（负数代表惩罚）
REACH_TARGET_REWARD : 10000       # 到达终点的奖励
TARGET_RADIUS : 2.5                 # 终点的领域半径
DISTANCE_CHANGE_REWARD_COE : 5000    # 每次离终点距离和上一次比较的差值的奖励系数
ANGLE_REWARD: -1
# CHATGPT
# laser_distance: 1.0
# target_distance: 1.0
# target_angle: 0.5
# collision: -5.0
# success: 10.0

# 
# obs_near_th : 1
# TARGET_RADIUS : 2.5
# REACH_TARGET_REWARD : 10
# obs_reward : -5
# DISTANCE_CHANGE_REWARD_COE: 5


DONE_DISTANCE : 1.                  # 判定episode结束的距离阈值
DONE_COLLISION : 1               # 判定episode结束的碰撞次数阈值
DONE_STEP_NUM : 72000               # 停止的迭代步数